### ISSUE TITLE
Invariant analogs of Applicative/Divisible and Alternative/Decidable?

### ISSUE THREAD

**Issue by RyanGlScott** [nfrisby/invariant-functors#10]
We all know about `Applicative` and `Alternative`:

``` haskell
class Functor f => Applicative f where
    pure  :: a -> f a
    (<*>) :: f (a -> b) -> f a -> f b

class Applicative f => Alternative f where
    empty :: f a
    (<|>) :: f a -> f a -> f a
```

And the `contravariant` package has analogs for these two classes in the `Data.Functor.Contravariant.Divisible` module:

``` haskell
class Contravariant f => Divisible f where
  divide  :: (a -> (b, c)) -> f b -> f c -> f a
  conquer :: f a

class Divisible f => Decidable f where
  lose   :: (a -> Void) -> f a
  choose :: (a -> Either b c) -> f b -> f c -> f a
```

The `invariant` package gives us the wonderful `Invariant` typeclass that brings together covariant and contravariant functors into a single abstraction. Can we similarly bring together `Applicative`/`Divisible` and `Alternative`/`Decidable`?

Some things to consider:
1. What would we name these typeclasses?
2. What would the laws be?

**Comment by RyanGlScott** [comment]
A very crude sketch, without any attempt at thinking about laws:

``` haskell
module Woven where

import Control.Applicative

import Data.Functor.Contravariant.Divisible
import Data.Functor.Invariant
import Data.Monoid (Endo(..))
import Data.Void

-------------------------------------------------------------------------------
-- The Woven class
-------------------------------------------------------------------------------

class Invariant f => Woven f where
  stitch :: a -> f a
  weave  :: (a -> b -> c) -> (c -> (a, b)) -> f a -> f b -> f c

stitchApplicative :: Applicative f => a -> f a
stitchApplicative = pure

weaveApplicative :: Applicative f => (a -> b -> c) -> (c -> (a, b)) -> f a -> f b -> f c
weaveApplicative f = const $ liftA2 f

instance Applicative f => Woven (WrappedFunctor f) where
  stitch = stitchApplicative
  weave  = weaveApplicative

stitchDivisible :: Divisible f => a -> f a
stitchDivisible = const conquer

weaveDivisible :: Divisible f => (a -> b -> c) -> (c -> (a, b)) -> f a -> f b -> f c
weaveDivisible = const divide

instance Divisible f => Woven (WrappedContravariant f) where
  stitch = stitchDivisible
  weave  = weaveDivisible

dividedW :: Woven f => f a -> f b -> f (a, b)
dividedW = weave (,) id

conqueredW :: Woven f => f ()
conqueredW = stitch ()

liftW :: Woven f => (a -> b) -> (b -> a) -> f a -> f b
liftW f g = weave (const f) ((,) () . g) conqueredW

liftW2 :: Woven f => (a -> b -> c) -> (c -> (a, b)) -> f a -> f b -> f c
liftW2 = weave

liftW3 :: Woven f => (a -> b -> c -> d) -> (d -> (a, b, c)) -> f a -> f b -> f c -> f d
liftW3 merge branch fa fb fc =
  weave (\(a, b) c -> merge a b c)
        (\d -> case branch d of (a, b, c) -> ((a, b), c))
        (dividedW fa fb) fc

unlessW :: Woven f => Bool -> f () -> f ()
unlessW p s = if p then stitch () else s

whenW :: Woven f => Bool -> f () -> f ()
whenW p s = if p then s else stitch ()

instance Woven Endo where
  stitch = Endo . const
  weave merge branch (Endo aa) (Endo bb) = Endo $ \c -> case branch c of
    (a, b) -> merge (aa a) (bb b)

-------------------------------------------------------------------------------
-- The Selective class
-------------------------------------------------------------------------------

class Woven f => Selective f where
  -- | If you choose not to decide, you still have made a choice.
  abstain  :: (a -> Void) -> f a
  judgment :: (a -> c) -> (b -> c) -> (c -> Either a b) -> f a -> f b -> f c

abstainAlternative :: Alternative f => (a -> Void) -> f a
abstainAlternative = const empty

judgmentAlternative :: Alternative f => (a -> c) -> (b -> c) -> (c -> Either a b) -> f a -> f b -> f c
judgmentAlternative ac bc _ fa fb = fmap ac fa <|> fmap bc fb

instance Alternative f => Selective (WrappedFunctor f) where
  abstain  = abstainAlternative
  judgment = judgmentAlternative

abstainDecidable :: Decidable f => (a -> Void) -> f a
abstainDecidable = lose

judgmentDecidable :: Decidable f => (a -> c) -> (b -> c) -> (c -> Either a b) -> f a -> f b -> f c
judgmentDecidable = const . const choose

instance Decidable f => Selective (WrappedContravariant f) where
  abstain  = abstainDecidable
  judgment = judgmentDecidable

instance Selective Endo where
  abstain f = Endo $ absurd . f
  judgment ac bc cab (Endo aa) (Endo bb) =
    Endo $ either (ac . aa) (bc . bb) . cab

chosenS :: Selective f => f a -> f b -> f (Either a b)
chosenS = judgment Left Right id

guardS :: Selective f => Bool -> f ()
guardS True  = stitch ()
guardS False = abstain (\x -> x `seq` undefined)

lostS :: Selective f => f Void
lostS = abstain id
```

**Comment by nfrisby** [comment]
My immediate reaction is to wonder how used these would be. How often would
profunctors' `Strong` and `Choice` classes not work? `Endo` seems like the
prime culprit in that scenario, but I wonder when `Monoid (P a a)` wouldn't
be in reach instead of requiring the type's definition itself to unify the
in and out types (as a single parameter).

I'll admit, though, that once we've got ins and outs, my intuition for sums
and products tends toward `Arrow`. Have you much experience with `Strong`
and `Choice`?

... The above was entirely focused on the `->` case. On the other hand, I
realize many functor combinators (e.g. `:*:`) applied to covariant and
contravariant functors would induce this structure. That suggests to me
that it's not so rare. Of course, the need to _abstract_ over such things
probably is even more rare than abstracting over invariant functors. But,
of course, I don't really know where to draw the line, if anywhere. (In the
abstracted case, these "simultaneous" versions could avoid repeated
traversals.)

That's my stream of consciousness reaction. What do you think? Is this
structure worth its weight in the library?

**Comment by RyanGlScott** [comment]
To be perfectly honest, I don't have a particular use case in mind for these classes. They popped into my mind when thinking about how, since `Invariant` gives us a way to map over any data structure of kind `* -> *`, regardless of variance, perhaps `Woven`/`Selective`/whatever-we-call-it could give us a way to _combine_ values of `* -> *`-kinded data structures, regardless of variance. I'm not sure how well the analogy holds up in this case.

You're certainly right in that these classes probably wouldn't at all be useful for manipulating `Endo`s, given that we already have tools for that. That was just the first nontrivial example of something I could think of that doesn't inherit an instance from `Applicative`/`Alternative`/_et al._ Perhaps they'd be more useful in a generic programming library... hard to say.

In any case, I certainly don't plan to add these to the library anytime soon, especially not until we (ever?) come up with satisfactory answers to the above questions. I was sort of hoping someone with more knowledge of category theoretic gubbins could chime in to see if this idea is at all tenable :)

**Comment by RyanGlScott** [comment]
Upon further thought, I think there's enough room for bikeshedding about the design of these classes to the point where I wouldn't want to add them to `invariant` (perhaps a separate package).
