### ISSUE TITLE
Endo-style profunctor wrapper

### ISSUE THREAD

**Issue by treeowl** [nfrisby/invariant-functors#11]
```haskell
newtype Expo p a = Expo { getExpo :: p a a }

instance Profunctor p => Invariant (Expo p) where
  ...
```

Is it useful? Dunno. But it seems an obvious thing.

**Comment by treeowl** [comment]
Actually, this is exactly the same wrapper that turns a semigroupoid into a semigroup and a category into a monoid. Does that exist somewhere? Does it have this instance?

**Comment by treeowl** [comment]
One option is `Join`, in `Data.Bifunctor.Join`. That module provides `instance Bifunctor p => Functor (Join p)`. We can give `instance Profunctor p => Invariant (Join p)`.

**Comment by RyanGlScott** [comment]
We already have a [more general instance](https://github.com/nfrisby/invariant-functors/blob/9f95da3d998b1040dfe89243ab421e540f7e759b/src/Data/Functor/Invariant.hs#L345-L347) for `Join` in `invariant`:

``` haskell
instance Invariant2 p => Invariant (Join p) where
  invmap f g = Join . invmap2 f g f g . runJoin
```

And [every `Profunctor` is also an `Invariant2`](https://github.com/nfrisby/invariant-functors/blob/9f95da3d998b1040dfe89243ab421e540f7e759b/src/Data/Functor/Invariant.hs#L802-L807). Does that work for your use case?

**Comment by treeowl** [comment]
I missed the transitive link. Sorry!
